What is a Data structure?

Data structure are different ways to organize ur data in computer that can be used effectively

S/W performance and effenciy is deponds upon the DS we used to store the data in system

Example: If we have a box contains different colour balls and we want to pick all the blue balls from box.

so we need to go each and every ball and check the ball is blue or not and if it blue we will pick it

we do the same job in another way that , 1st arrange the ball according to it colour while placing the balll in box , so that that we can pick the ball whatever we want directly from box. This is the place where Data Structres comes into picture


What is an Algorithm?

Set of instructions to perform the task

example: buy a coffee from starbucks

step1: go to starbucks
step2: choose the coffee u want
step3: order it
step4: pay for it
step5: take it and enjoy


Why companies look at DSA in intervies?
* Problem solving Skill
* basic concepts for s/w developer

Type of DS:
* Primitivie DS:
-> Basci data types that they are not broken into simple data types
-> has fixed size
-> small in size
-> simple operation
-> present in memoery as simple values
* Integer
* Float
* String
* Boolean

* Non primitive:
-> more complex and broken into small data types
-> pointers to other memory locations
-> it is classifed into 2 types
1. Linear data Structures
-> elements are arranged in sequental order and connects to next elemnt
* List
* Tuple
* Array
* Linked List
* stack
* Queue

2. Non Linear DS:
-> not connected in linear fassiona and connected to one or more other elements
* Set
* Dictonary
* Tree
* Graph

Bulit in DS: List, Tuple, set, Dictonary
user defined DS: rest all user defined




Types of Algo:
*Sorting
*search
*Graph
*DP
*Divide and conquer
*Recursive

Lecture 2 Recursion

What is Recursion?

A way of solving a problem by having a function calling itself

example: Russain doll

Rules for recursion:
1. perform same operation many times with different I/P 
2. every time try with smaller I/P to make the problem smaller
3. Base Condition: to stop the recursion and stop infinate loop


In [1]:
#example
def RussianDoll_open(doll):
    if doll==1:
        print("All dolls are open")
    else:
        RussianDoll_open(doll-1)

In [2]:
RussianDoll_open(5)

All dolls are open


Why Recursion?
 * Recursive Thinking
 * Using trees and graphs
 * Interviews
 * used in many Algos
 


How Recursion works ?
1. a method to call it self
2. Base condition to exit from infinate loop


In [4]:
def m1():
    m2()
    print("Let do it")
def m2():
    m3()
    print("Welcome to DSA with python")
def m3():
    print("Hello World,")
m1()

Hello World,
Welcome to DSA with python
Let do it


In [4]:
m1()

Hello World,
Welcome to DSA with python
Let do it


Recurssive vs Iterative 

Space: 0 1
Time: 0 1
easy to code: 1 0

In [5]:
def pow2(n):
    if n==0:
        return 1
    else:
        p=pow2(n-1)
        return p*2
pow2(10)

1024

In [6]:
def pow2(n):
    i=0
    p=1
    while i<n:
        p*=2
        i+=1
    return p
 
pow2(1)

2

 when to use recursion 
 
 * easy to break into subproblems
 * ok with etra time and space
 * quick insted of efficent
 * traverse a tree
  
  not recursion (vise-versa)
  

In [7]:
#find the sum of digits of given number
def SumofDigits(n):
    assert n>=0 and int(n)==n," Please enter postive integer"
    if n ==0:
        return n
    else:
        return int(n%10)+SumofDigits(n//10)
    

In [8]:
SumofDigits(75)

12

In [9]:
#calculate the powe of a number using recursion
def power(base,exp):
    assert int(exp)==exp , "Please enter exponent as intege"
    if exp==0:
        return 1
    elif exp<0 and base > 0:
        return 1/ base * power(base,exp+1)
    else:
        return base * power(base,exp-1)

In [10]:
power(7,5)

16807

In [6]:
#GCD of two numbers (using Equladian algorithm)
def gcd(a,b):
    assert int(a)==a and int(b)==b, "numbers must be integegers"
    if a or b <0:
        a=abs(a)
        b=abs(b)
    if b==0:
        return a
    return gcd(b,a%b)
gcd(35,55)

5

In [7]:
#decimal to binary
def dtob(n):
    assert int(n)==n, " please enter an integer"
    if n in[0,1]:
        return n
    else:
        return int(n%2 + 10*dtob(n//2))
dtob(8)

1000

In [13]:
#POWER SOLUTION
def power(base, exponent):
    if exponent == 0:
        return 1
    return base * power(base, exponent-1)
power(2,7)

128

In [14]:
#FACTORIAL SOLUTION
def factorial(num):
    if num <= 1:
        return 1
    return num * factorial(num-1)
factorial(5)

120

In [15]:
#PRODUCT OF ARRAY SOLUTION
def productOfArray(arr):
    if len(arr) == 0:
        return 1
    return arr[0] * productOfArray(arr[1:])
a=[1,2,3,4,5,6,7,8]
productOfArray(a)

40320

In [16]:
#RECURSIVE RANGE SOLUTION
def recursiveRange(num):
    if num <= 0:
        return 0
    return num + recursiveRange(num - 1)
recursiveRange(10)

55

In [8]:
#FIBONACCI SOLUTION
def fib(num):
    if (num < 2):
        return num
    return fib(num - 1) + fib(num - 2)
fib(6)

8

Big O Notation

Time complexity: the amount of Time taken to complete a task

Big O (Worst case): less or equal to worst case
Big Omega: more than best case
Big tetha: winthin worst and best case

O(1): constant (number of operations constant)

O(N): Linear(find number from 1 to n)

O(LogN) Logarthmic (find element in sorted array)

O(N^2) qudratic (Nested loop)

O(2^n): Exponential ( Double recursion in fibonacci)


O(1): picking a card in cards

O(N): picking a specified card in deck of cards

O(N^2): picking a specified card from all the sets

O(LogN): binary search

Time : O(1) < O(LogN) <O(N) < O(NLogN) < O(N^2) < O(2^n)



Space Complexity: The amout of space (Stack Memory) requred to complete a task 


Array: Colction of simmillar type of objects
example: Books in library rack

* Array can store data of specified data tupe only
* Element of array are continous
* Each element has a unique index
* The size is predefined and cannot modified

Why Array ?

which can store a fixed size of particular data type and avoid mutliple declaritions


Types of Array:
1. 1-D Array
2. Multi-D Array



In [9]:
#creation of array
# Assign it a varaiable
#define type of elements to store
#define the size 

from array import *
arr1 = array('i',[1,2,3,4,5,6])
print(arr1)

arr2= array('d',[1.2,1.3,1.4,1.15])
print(arr2)


array('i', [1, 2, 3, 4, 5, 6])
array('d', [1.2, 1.3, 1.4, 1.15])


Type Code      type
* 'b'  Signed char
*  'B' Unsigned char
* 'u'  Unicode
*  'h' signed short
*  'H" Undigned short
* 'i' Signed int
*  'I' Unsigned Int
*  'l' signed long
*  'L' unsigned Long
*  'q' signed long long
*  'Q' Unsigned long long
*  'f' float
*  'd' double

In [11]:
#Array insertion
#end of array
arr1.insert(6,7) #index, value
print(arr1)

arr1.insert(6,2)
print(arr1)

array('i', [1, 2, 3, 4, 5, 6, 7, 2, 7])
array('i', [1, 2, 3, 4, 5, 6, 2, 7, 2, 7])


In [20]:
#start of array
arr1.insert(0,0)
print(arr1)


array('i', [0, 1, 2, 3, 4, 5, 6, 7])


In [21]:
#ad middel of array

arr1.insert(4,6)
print(arr1)

array('i', [0, 1, 2, 3, 6, 4, 5, 6, 7])


In [22]:
#array Traversal

def traverse (arr):
    for i in arr:
        print(i)
traverse(arr1)
#O(n )

0
1
2
3
6
4
5
6
7


In [23]:
#Access elemrnt in array

def access(arr,x):
    assert x<len(arr),"enter index is out of index"
    print(arr[x])

access(arr1,5)

4


In [24]:
#searching element in array
#1 search by index
#2 if array is sorted use binary search

def search(arr, x):
    for i, val in enumerate(arr):
        if val == x:
            return "Element found at index " + str(i)
    return "Element not found"

search(arr1,5)

'Element found at index 6'

In [25]:
#deleting a element in array

def delete(arr,x):
    assert x in arr, "element not in array"
    arr.remove(x)
    print(arr)
delete(arr1,6)

array('i', [0, 1, 2, 3, 4, 5, 6, 7])


Operation      / Time /  Space
* Create a empty array O(1), O(n)
* Insert    O(1)/O(n), O(1)
* Traverse. O(n), O(1)
* Accessing. O(1), O(1)
* Searching  O(n), O(1)
* delete   O(1)/O(n), O(1)

Array Operations:

* Append: adds ur element at end of array
* Insert: insert element at any position
* Extend: we can append the array to our current array
* fromlist() : appends list to array
* Remove: removes the 1st occurance of given element
* Pop: removes last element
* index(): gives index of element in array
* Reverse(): 
* Buffer_info(): start of buffer in memory and number of elements
* Count(): count the element in given array
* tostring(): convert array to string
* fromstring(): append string to current array
* tolist(): convert array to list
* [:] : slice operator


In [26]:
#2-D Array

import numpy as np

arr2D= np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])
print(arr2D)
 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
#adding column / row in 2D array
#np.insert(array, index, values, axis 0 if row, 1 if column)
arr2d= np.insert(arr2D,0,[13,14,15,16,],axis=0)
print(arr2d)
arr2d = np.insert(arr2d,0,[17,18,19,20],axis=1)
print(arr2d)

[[13 14 15 16]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[17 13 14 15 16]
 [18  1  2  3  4]
 [19  5  6  7  8]
 [20  9 10 11 12]]


In [28]:
#Access element in 2-D array

def access(arr,row, column):
    if row >=len(arr) or column >=len(arr[0]):
        print("enter correct index")
    else:
        print(arr[row][column])
access(arr2d,3,3)

11


In [29]:
#trverse in 2-D array

def treverse (arr):
    for i in range(len(arr)):
        for j in range(len(arr[0])):
            print(arr[i][j])

treverse(arr2d)

17
13
14
15
16
18
1
2
3
4
19
5
6
7
8
20
9
10
11
12


In [30]:
# search a elemnt in 2D array

def search(arr, x):
    for i in range(len(arr)):
        for j in range(len(arr[0])):
            if arr[i][j]==x:
                return " element found"
    return "element not found"

search(arr2D,6)

' element found'

In [31]:
#deletion a row/colum in 2 D array
#delete(array,row/column, axis 0 for row, 1 for column)
arr2d= np.delete(arr2d,0,axis=0)
print(arr2d)

[[18  1  2  3  4]
 [19  5  6  7  8]
 [20  9 10 11 12]]


 When to use & avoid arrays:
 
 Use:
 * multiple variables of same data type
 * access random varable 
 
 Avoid:
 * different data types
 * reserve memory
 

List: is a DS that holds an ordered collection of items




In [32]:

x=[1,2,3,"Hi","hell0",1.43]
print(x)

[1, 2, 3, 'Hi', 'hell0', 1.43]


In [33]:
#Traversal list

def Traversal (l1):
    for i in l1:
        print(i)
Traversal(x)

1
2
3
Hi
hell0
1.43


In [34]:
#exits in list

def exit(l1,x1):
    if x1 in l1:
        return "element in list"
    return "element not in list"

exit(x,5)

'element not in list'

In [35]:
#update / insert list
print(x)
#update O(1)
x[1]=5
print(x)

#insert O(n)
x.insert(3,7)
print(x)

#append O(1)
x.append(75)
print(x)

#extend O(n)
y=[5,6,7,8,9,10]
x.extend(y)
print(x)

[1, 2, 3, 'Hi', 'hell0', 1.43]
[1, 5, 3, 'Hi', 'hell0', 1.43]
[1, 5, 3, 7, 'Hi', 'hell0', 1.43]
[1, 5, 3, 7, 'Hi', 'hell0', 1.43, 75]
[1, 5, 3, 7, 'Hi', 'hell0', 1.43, 75, 5, 6, 7, 8, 9, 10]


In [36]:
#slice and deletion of list

x[0:3]=["Remo",75,89]
print(x)


['Remo', 75, 89, 7, 'Hi', 'hell0', 1.43, 75, 5, 6, 7, 8, 9, 10]


In [37]:
#pop
#need index of elment to delete
#if no index provided deletes lat element
x.pop(4)
print(x)


['Remo', 75, 89, 7, 'hell0', 1.43, 75, 5, 6, 7, 8, 9, 10]


In [38]:
#delete
#needs index
del x[4:6]
print(x)
#remove

['Remo', 75, 89, 7, 75, 5, 6, 7, 8, 9, 10]


In [39]:
#remove
#if know value we can remove directly

x.remove("Remo")
print(x)

[75, 89, 7, 75, 5, 6, 7, 8, 9, 10]


In [40]:
#searching element in list
#in operator
#searching algo

#in
if 75 in x:
    print(x.index(75))

#linear search

def search(l1,x):
    for i in l1:
        if i==x:
            return l1.index(x)
    return "not in list"

search(x,8)

0


7

In [41]:
#list operations

#+ Concatinate list
y=[1,23,7,"hi"]
x=x+y
print(x)


[75, 89, 7, 75, 5, 6, 7, 8, 9, 10, 1, 23, 7, 'hi']


In [42]:
#* operator (repats number of times)

x=x*2
print(x)

[75, 89, 7, 75, 5, 6, 7, 8, 9, 10, 1, 23, 7, 'hi', 75, 89, 7, 75, 5, 6, 7, 8, 9, 10, 1, 23, 7, 'hi']


In [43]:
#len length of list
print(len(x))

28


In [44]:
#max
x=[1,2,3,4,5,8,9,75,89,3,4,57]
max(x)



89

In [45]:
#min
min(x)

1

In [46]:
#sum
sum(x)

260

In [47]:
#count

x.count(75)

1

In [48]:
#list from string

x="Hello Remo"
x=list(x)
print(x)

['H', 'e', 'l', 'l', 'o', ' ', 'R', 'e', 'm', 'o']


In [49]:
#split
x="Hello Remo"
x=x.split()
print(x)

x="Hello.Remo.hi"
x=x.split('.')
print(x)



['Hello', 'Remo']
['Hello', 'Remo', 'hi']


In [50]:
#join
y='.'.join(x)
print(y)

Hello.Remo.hi


array vs list
* Both are mutable
* arrays are good for arthematic operations



In [51]:
#missing Numbers

def find_missing(l1,n):
    s=(n*(n+1))/2
    s1=sum(l1)
    miss= s-s1
    return miss

In [52]:
#Pairs /Two sum

def pairs(l1,t):
    for i in range(len(l1)):
        for j in range(i+1,len(l1)):
            if l1[i]==l1[j]:
                continue
            if l1[i]+ l1[j]==t:
                print(i,j)
x=[1,2,3,2,3,4,5,6]
t=6
pairs(x,t)

0 6
1 5
3 5


In [53]:
#Finding a number in array

def find(arr,x):
    for i in arr:
        if i==x:
            return l1.index(i)
    return "eelement not found"
        

In [12]:
#rotate a matrix 90 degree
import numpy as np
def rotate_matrix(matrix):
    n = len(matrix)
    # Transpose the matrix using zip
    matrix[:] = list(zip(*matrix))
    print(matrix)
    # Reverse each row of the transposed matrix
    for i in range(n):
        matrix[i] = matrix[i][::-1]
    return matrix

x=np.array([[1,2,3],[4,5,6],[7,8,9]])
#print(list(zip(x)))
print(list(zip(*x)))
rotate_matrix(x)
print(x)

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[7 4 1]
 [8 5 2]
 [9 6 3]]


Dictonary: Key & value pairs

example: order id of ur order in KFC /Burger King

Key: order id

value: details of ur order

In [55]:
#Creation of dictonary
#dictonary is unorder collection of key value pairs
x=dict()
print(x)

x={}
print(x)

x={1:"Hi",2:"hello",3:"ola"}
print(x)

{}
{}
{1: 'Hi', 2: 'hello', 3: 'ola'}


In [56]:
#access the element in dict
# we can access using. key value
print(x[1])
print(x[2])

Hi
hello


Python dict are implemented by using Hash function

Hash table is way of doing key-value lookups

Why dict unordered?

we use hash function and array to store the dict , so hash function generate the hash code based on code it is stored, so hash code may be random so it is unordered



In [57]:
#update and insert dict

#update
x[2]="remo"
print(x)

#if key exits it will update else it will create ne key pairs

x[4]="Nwe York"
print(x)

{1: 'Hi', 2: 'remo', 3: 'ola'}
{1: 'Hi', 2: 'remo', 3: 'ola', 4: 'Nwe York'}


In [58]:
#traverse dict

def treverse (dic):
    for key in dic:
        print(key,dic[key])
treverse(x)

1 Hi
2 remo
3 ola
4 Nwe York


In [59]:
#search element in dict

def find(dic,x):
    for key in dic:
        if dic[key]==x:
            return key, dic[key]
    return " not in dic"

find(x,"remo")

(2, 'remo')

In [60]:
#delete element in dic

#pop(key)
x.pop(3)
print(x)

{1: 'Hi', 2: 'remo', 4: 'Nwe York'}


In [61]:
#popitem()
print(x.popitem())


(4, 'Nwe York')


In [62]:
#clear() all elemnts deleted
x.clear()
print(x)

{}


In [63]:
#del
x={1: 'Hi', 2: 'remo', 4: 'Nwe York'}
del x[1]
print(x)

{2: 'remo', 4: 'Nwe York'}


In [64]:
#delte all elemrnt in dict

del x
#print(x)

In [65]:
#fromkeys
y={}.fromkeys([1,2,3],[0,1,2])
print(y)

{1: [0, 1, 2], 2: [0, 1, 2], 3: [0, 1, 2]}


In [66]:
#get
print(y.get(1))

[0, 1, 2]


In [67]:
#items

print(y.items())

dict_items([(1, [0, 1, 2]), (2, [0, 1, 2]), (3, [0, 1, 2])])


In [68]:
#keys

print(y.keys())

dict_keys([1, 2, 3])


In [69]:
#setdefault
print(y.setdefault(1,"hello"))
print(y.setdefault(4,"hello"))
print(y)

[0, 1, 2]
hello
{1: [0, 1, 2], 2: [0, 1, 2], 3: [0, 1, 2], 4: 'hello'}


Dictonary methods

* Clear(): clears all elements in Dict
* Copy(): creates a copy of dict
* fromkeys()
* get():
* Items():
* Keys ():
* popitem():
* setdefault():
* pop()
* Values ():
* update():

In [70]:
#dict operations
#in operators works with keys defualt

#len()
print(len(y))

#all()
#true only all keys are true else false
print(all(y))

#any
#false only all are false, else true
print(any(y))


4
True
True


Tuple: Sequane of python objects which are immutable

-> comparable and hashable


In [71]:
#tuple creation

x= "a","b","c",1
print(x)

x=("a","b","c",1)
print(x)

#tuple contains single element:

y=('a',)
print(y)

#using tuple

x=tuple("Hello")
print(x)

('a', 'b', 'c', 1)
('a', 'b', 'c', 1)
('a',)
('H', 'e', 'l', 'l', 'o')


In [72]:
#tuple in memory: 
#access tuple

print(x[2])

l


In [73]:
#traverse tuple

for i in x:
    print(i)

H
e
l
l
o


tuple operations

* +: concatenation
* Len():


#Linked list
 
It is a form of a sequential collection & it does not have any order , it is made up of independent nodes that may contain any type of data & each node has a reference tot he nect node in the link

example: train, we have link b/w each boggi, 1st is called as head and last is called as tail


Linked list vs array
Linked list:
-> each element in linked list is independent
-> variable size
-> insertion and deletion is faster & efficent
-> access is more diffcult than array

Array:
-> elements are dependent
-> fixed size
-> access is easy



Types of Linked list

1. Single linked list: each nodes stores data and reference of next node

2. circular linked list: same as single linked list but the refernce of last node is pointed to the 1st node

example: 4 player chess game

3. Double linked list: each node has data and 2 reference( both directions) each node stores the reference of previous & next nodes

example: implementing music player

4. Double circular linked list: simillar to circular linkked list, last node address is referenced to 1st node

example: taskbar of our desktop




In [74]:
#linked list in memory: not continous in memory

#single linked list

#creation
#insert a node 
#beging of list
#middle of list
#end of list
class Node:
    def __init__(self, value=None):
        self.value = value
        self.next = None

class SLinkedList:
    def delete(self,loc):
        if self.head is None:
            return " list is empty unable to delete"
        else:
            if loc==0:
                if self.head==self.tail:
                    self.head=None
                    self.tail=None
                else:
                    self.head=self.head.next
            elif loc==-1:
                if self.head==self.tail:
                    self.head=None
                    self.tail=None
                else:
                    node=self.head
                    while node is not None:
                        if node.next==self.tail:
                            break
                        node=node.next
                    node.next=None
                    self.tail=node
            else:
                tempnode=self.head
                i=0
                while i<loc-1:
                    tempnode= tempnode.next
                    i+=1
                nextNode=tempnode.next
                tempnode.next=nextNode.next
                
            
    def search(self,x):
        if self.head==x or self.tail==x:
            return "exists"
        else:
            node=self.head
            while node is not None:
                if node.value== x:
                    return node.value
                node=node.next
            return " not in list"

    def __init__(self):
        self.head = None
        self.tail = None
        
    def __iter__(self):
        node = self.head
        while node:
            yield node
            node = node.next
            
    def insert(self, value, loc):
        new_node = Node(value)
        if self.head is None:
            self.head = new_node
            self.tail = new_node
        else:
            if loc == 0:
                new_node.next = self.head
                self.head = new_node
            elif loc == -1:
                self.tail.next = new_node
                self.tail = new_node
            else:
                temp_node = self.head
                index = 0
                while index < loc - 1:
                    temp_node = temp_node.next
                    index += 1
                next_node = temp_node.next
                temp_node.next = new_node
                new_node.next = next_node
        

slist = SLinkedList()
slist.insert(1, 1)
slist.insert(2, 1)
slist.insert(3,2)
slist.insert(4,1)
print([node.value for node in slist])


[1, 4, 2, 3]


In [75]:
#traverse linked list
def traverse(self):
    if self.head is None:
        return "empty list"
    else:
        node= self.head
        while node is not None:
            print(node.value)
            node=node.next
traverse(slist)

1
4
2
3


In [76]:
slist.search(4)

4

In [77]:
slist.delete(1)
print([node.value for node in slist])

[1, 2, 3]


In [78]:
slist.delete(2)
print([node.value for node in slist])

[1, 2]


In [79]:
class Node:
    def __init__(self, value=None):
        self.value = value
        self.next = None
    
class CircularSinglyLinkedList:
    def __init__(self):
        self.head = None
        self.tail = None
    
    def __iter__(self):
        node = self.head
        while node:
            yield node
            if node.next == self.head:
                break
            node = node.next
    
    def create_csl(self, val):
        node = Node(val)
        if self.head is None:
            self.head = node
            self.tail = node
            node.next = self.head
        else:
            self.tail.next = node
            self.tail = node
            node.next = self.head
    
    def display(self):
        if self.head is None:
            print("List is empty")
        else:
            print("Nodes of the Circular Singly Linked List:")
            for node in self:
                print(node.value)
    def insercsl(self,val,loc):
        if self.head is None:
            return "Head is None"
        else:
            newnode=Node(val)
            if loc==0:
                newnode.next=self.head
                self.head=newnode
                self.tail.next=newnode
            elif loc==-1:
                newnode.next=self.tail.next
                self.tail.next=newnode
                sel.tail=newnode
            else:
                tempnode=self.head
                index=0
                while index<loc-1:
                    tempnode=tempnode.next
                    index+=1
                nextnode=tempnode.next
                tempnode.next=newnode
                newnode.next=nextnode
    def traversescsl(self):
        if self.head is None: 
            return " No element in CSL"
        else:
            temp=self.head
            while temp==self.tail:
                print(temp.value)
                temp=temp.next
    def searchcsl(self,x):
        if self.head is None:
            return "no elemnet in list"
        else:
            temp=self.head
            while temp!=self.tail:
                if temp.value==x:
                    return "element found"
                temp=temp.next
            return "elemnet not on CSL"
    def deletecsl(self, loc):
        if self.head is None:
            return "CSL is empty"
        else:
            if loc == 0:
                if self.head == self.tail:
                    self.head.next = None
                    self.head = None
                    self.tail = None
                else:
                    self.head = self.head.next
                    self.tail.next = self.head
            elif loc == 1:
                if self.head == self.tail:
                    self.head.next = None
                    self.head = None
                    self.tail = None
                else:
                    node = self.head
                    while node.next != self.tail:
                        node = node.next
                    node.next = self.head
                    self.tail = node
            else:
                temp = self.head
                index = 0
                while index < loc-1:
                    temp = temp.next
                    index += 1
                nextnode = temp.next
                temp.next = nextnode

csl = CircularSinglyLinkedList()
csl.create_csl(1)
csl.create_csl(2)
csl.create_csl(3)
csl.display()
csl.insercsl(3,3)
csl.display()
csl.insercsl(10,2)
csl.display()
#csl.traversescsl()
#csl.searchcsl(10)
csl.deletecsl(1)
csl.display()



Nodes of the Circular Singly Linked List:
1
2
3
Nodes of the Circular Singly Linked List:
1
2
3
3
Nodes of the Circular Singly Linked List:
1
2
10
3
3
Nodes of the Circular Singly Linked List:
1
2
10


In [80]:
#double Linked List

class Node:
    def __init__(self, value=None):
        self.value=value
        self.next=None
        self.prev=None
class DLL:
    def __init__(self):
        self.head=None
        self.tail=None
    def __iter__(self):
        node=self.head
        while node:
            yield node
            node=node.next
    def createdll(self,val):
        node=Node(val)
        node.prev=None
        node.next=None
        self.head=node
        self.tail=node
        return "Node is created"
    def insertdll(self,val,loc):
        if self.head is None:
            print("ca not onseterd")
        else:
            newnode=Node(val)
            if loc==0:
                newnode.prev=None
                newnode.next=self.head
                self.head.prev=newnode
                self.head=newnode
            if loc==-1:
                newnode.next=None
                newnode.prev=self.tail
                self.tail.next=newnode
                self.tail=newnode
            else:
                temp=self.head
                index=0
                while index < loc-1:
                    temp=temp.next
                    index+=1
                newnode.next=temp.next
                newnode.prev=temp
                newnode.next.prev=newnode
                temp.next=newnode
    def traversaldll(self):
        if self.head is None:
            return " No elent"
        else:
            node=self.head
            while node:
                print(node.value)
                node=node.next
    def revtraverse(self):
        if self.head is None:
            return " no element"
        else:
            node=self.tail
            while node:
                print(node.value)
                node=node.prev
    def searchdll(self,x):
        if self.head is None:
            return "No element"
        else:
            node= self.head
            while node:
                if node.value==x:
                    return " elemnt found"
                node=node.next
            return " not in DLL"
    def deletedll(self, loc):
        if self.head is None:
            return " No element to delete"
        else:
            if loc==0:
                if self.head==self.tail:
                    self.head=None
                    self.tail=None
                else:
                    self.head=self.head.next
                    self.head.prev=None
            if loc==1:
                if self.head==self.tail:
                    self.head=None
                    self.tail=None
                else:
                    self.tail=self.tail.prev
                    self.tail.prev=None
            else:
                temp=self.head
                i=0
                while i < loc-1:
                    temp=temp.next
                    i+=1
                temp.next=temp.next.next
                temp.next.prev=temp
                return "deleted"
                
                    
                    
                
                
            
                
                
            
            
dll = DLL()
dll.createdll(1)
dll.insertdll(0, 1)
dll.insertdll(2, 1)
dll.insertdll(3, 2)

node_values = [node.value for node in dll]
print(node_values)
dll.traversaldll()
print("\n")
dll.revtraverse()
dll.searchdll(2)
dll.searchdll(7)
dll.deletedll(2)

[1, 0, 3, 2]
1
0
3
2


2
3
0
1


'deleted'

In [81]:
#linked list interview questions
from random import randint
class Node:
    def __init__(self,value=None):
        self.value=value
        self.next=None
        self.prev=None
    def __str__(self):
        return str(self.value)
class LinkedList:
    def __init__(self):
        self.head=None
        self.tail=None
    def __iter__(self):
        node=self.head
        while node:
            yield node
            node=node.next
    def __str__(self):
        values= [str(x.value)for x in self]
        return '->'.join(values)
    def __len__(self):
        res=0
        node=self.head
        while node:
            res+=1
            node=node.next
    def add(self, value):
        if self.head is None:
            node=Node(value)
            self.head=node
            self.tail=node
        else:
            self.tail.next=Node(value)
            self.tail=self.tail.next
        return self.tail
    def generate(self,n,min_val,max_val):
        self.head=None
        self.tail=None
        for i in range(n):
            self.add(randint(min_val,max_val))
        return self
    #from LinkedList import LinkedList
    
Ill=LinkedList()
Ill.generate(10,0,50)
print(Ill)

24->39->22->43->50->14->24->21->27->35


In [82]:
#remove dupilcates from linked list

#from LinkedList import LinkedList
def removedup(ll):
    if ll.head is None:
        return
    else:
        node=ll.head
        visited=set([node.value])
        while node.next:
            if node.next.value in visited:
                node.next=node.next.next
            else:
                visited.add(node.next.value)
            return ll
Ill=LinkedList()
Ill.generate(10,0,5)
print(Ill)
ll=Ill
removedup(ll)
print(ll)

    
                

5->5->5->4->0->3->1->1->1->4
5->5->4->0->3->1->1->1->4


#Stack

* The stack DS follow LIFO(Last in first out)
example: back button on browser, 

* why stack: our computer memory is a stack memory

Stack Operations:

* Create Stack
* Push
* Pop
* Peak
* IsFull
* delete


In [83]:
#stack creation
#list list with size, linked list

#stack using list
# easy
# speed problem when it grows

#using list

class Stack:
    def __init__(self):
        self.list=[]
        
    def __str__(self):
        val=self.list.reverse()
        val=[str(x) for x in self.list]
        return '\n'.join(val)
    def isempty(self):
        if self.list==[] :
            return True
        return False
    def push(self,val):
        self.list.append(val)
        return str(val)+" is pushed into stack"
    def pop(self):
        if self.list ==[]:
            return " no elemnt in stack to pop"
        else:
            return self.list.pop()
    def peak(self):
        if self.list==[]:
            return "stack is empty"
        else:
            return self.list[-1]
    def delete(self):
        if self.list==[]:
            return "stack is empty"
        else:
            self.list=[]
        

st=Stack()
print(st.isempty())
st.push(5)
st.push(3)
st.push(1)
st.push(2)
st.push(4)
st.pop()
st.peak()
st.delete()
st.peak()

True


'stack is empty'

In [84]:
#using list with size

class Stack:
    def __init__(self,size):
        self.size=size
        self.list=[]
    def __str__(self):
        val=self.list.reverse()
        val=[str(x) for x in self.list]
        return '\n'.join(val)
    def isempty(self):
        if self.list ==[]:
            return True
        else:
            return False
    def isfull(self):
        if len(self.list)==self.size:
            return True
        else:
            return False
    def push(self, val):
        if self.isfull():
            return "stack is full"
        else:
            self.list.append(val)
            return str(val) +" is pushed into stack"
    def pop(self):
        if self.isempty():
            return "stack is empty"
        else:
            return self.list.pop()
    def peak(self):
        if self.list==[]:
            return "stack is empty"
        else:
            return self.list[-1]
    def delete(self):
        if self.list==[]:
            return "stack is empty"
        else:
            self.list=[]
st=Stack(4)
print(st.isempty())
st.push(5)
st.push(3)
st.push(1)
st.push(2)
st.push(4)
st.pop()
st.peak()
st.delete()
st.peak()

True


'stack is empty'

In [85]:
#using linked list

class Node:
    def __init__(self,value=None):
        self.value=value
        self.next=next
class LinkedList:
    def __init__ (self):
        self.head=None
    
    def __iter__(self):
        node=self.head
        while node:
            yield node.value
            node=node.next
class Stack:
    def __init__ (self):
        self.stack= LinkedList()
        
    def isempty(self):
        if self.stack.head==None:
            return True
        else:
            return False
    def push(sel,val):
        node=Node(value)
        node.next=self.stack.head
        self.stack.head=node
    
    def pop(self):
        if self.isempty():
            return " Stack is empty"
        else:
            nval=self.stack.head.value
            self.stack.head=self.stack.next
            return nval
    def peak (self):
        if self.isempty():
            return " Stack is empty"
        else:
            return self.stack.head.value
        
    def delete (self):
        if self.isempty():
            return " Stack is empty"
        else:
            self.stack.head = None


        
            

Queue: DS that store data in FIFO

example : Queue at bus stop

Why: shedule processing

Applicaltion call center

Operations:
* Create Queue
* Enqueue
* Dequeue
* Peak
* is Empty
* is full
* delete queue

In [2]:
#queue with list no size limit

class Queue:
    def __init__(self):
        self.q=[]
    def __str__(self):
        val=[str(x) for x in self.q]
        return " ".join(val)
    def isempty(self):
        if self.q==[]:
            return True
        else:
            return False
    def enqueue(self,val):
        self.q.append(val)
    def dequeue(self):
        if self.isempty():
            return " Queue is empty"
        else:
            return self.q.pop(0)
    def peak(self):
        if self.isempty():
            return " Queue is empty"
        else:
            return self.q[-1]
        
        
q=Queue()
print(q.isempty())
q.enqueue(1)
q.enqueue(2)
q.enqueue(3)
print(q)
q.dequeue()
print(q)
print(q.peak())


True
1 2 3
2 3
3


In [87]:
#queue with list size limit

class CQueue:
    def __init__(self,size):
        self.size=size
        self.q=[None]*size
        self.start=-1
        self.top=-1
        
    def __str__(self):
        val=[str(x) for x in self.q]
        return " ".join(val)
    def isfull(self):
        if self.top +1 ==self.start:
            return True
        elif self.start==0 and self.top +1==self.size:
            return True
        else:
            return False
    def isempty(self):
        if self.top==-1:
            return True
        else:
            return False
    def enqueue(self,val):
        if self.isfull():
            return "Q is full"
        else:
            if self.top +1 ==self.size:
                self.top=0
            else:
                self.top+=1
                if self.start==-1:
                    self.start=0
                self.q[self.top]=val
        
    def dequeue(self):
        if self.isempty():
            return " Queue is empty"
        else:
            x=self.q[self.start]
            start=self.start
            if self.start==self.top:
                sel.start==-1
                self.top==-1
            elif self.start-1==self.size:
                self.top=-1
            else:
                self.start +=1
            self.q[start]=None
            return x
    def peak(self):
        if self.isempty():
            return " Queue is empty"
        else:
            return self.q[self.start]
        
        
        
q=CQueue(5)
print(q.isempty())
q.enqueue(1)
q.enqueue(2)
q.enqueue(3)
print(q)
q.dequeue()
print(q)
print(q.peak())


True
1 2 3 None None
None 2 3 None None
2


In [88]:
#Q with Linked list

class Node:
    def __init__(self,val):
        self.val=val
        self.next=None
    def __str__(self):
        val=[str(x) for x in self.q]
        return " ".join(val)
class Queue:
    def __init__(self):
        self.head=None
        self.tail=None
        self.next=None
    def __iter__(self):
        node=self.head
        while node:
            yield node.val
            node=node.next
class Q:
    def __init__(self):
        self.Queue=Queue ()
    def __str__(self):
        val=[str(x) for x in self.Queue]
        return " ".join(val)
    def enq(self,val):
        node=Node(val)
        if self.Queue.head==None:
            self.Queue.head=self.Queue.tail=node
        else:
            self.Queue.tail.next=node
            self.Queue.tail=node
    def isempty(self):
        if self.Queue.head==None:
            return True
        else:
            return False
    def deq(self):
        if self.isempty():
            return "Q is empty"
        else:
            temp= self.Queue.head
            if self.Queue.head==self.Queue.tail:
                self.Queue.head=self.Queue.tail=None
            else:
                self.Queue.head=self.Queue.next
            return temp
    def peak(self):
        if self.isempty():
            return "Q is empty"
        else:
            return self.Queue.head
    def delete(self):
        self.Queue.head=self.Queue.tail=None
            
        
        
            
            
q=Q()
q.enq(1)
q.enq(2)
q.enq(3)
print(q)
q.deq()
print(q)
q.peak()
    

1 2 3



'Q is empty'

#collections

collection.deque

methods:

-> deque()
-> append()
-> popleft()
-> clear


In [89]:
from collections import deque
q= deque(maxlen=5)
print(q)
q.append(1)
q.append(2)
q.appendleft(3)
print(q)
q.count(1)
q.pop()
print(q)
q.

deque([], maxlen=5)
deque([3, 1, 2], maxlen=5)
deque([3, 1], maxlen=5)


Python Queue Module

FIFO Q
Lifo Q (stack)
Priority Q



In [7]:
import queue as q

cq=q.Queue(maxsize=5)
print(cq.empty())
print(cq.full())
cq.put(1)
cq.get(1)

True
False


1

In [91]:
#stack and Q interview Questions

#three in one

class multistack:
    def __init__(self,size):
        self.nstacks=3
        self.stack=[0]*(size*self.nstacks)
        self.sizes=[0]* self.nstacks
        self.size=size
    
    def isfull(self,snum):
        if self.sizes[snum]==self.size:
            return True
        else:
            return False
    def isempty(self,snum):
        if self.sizes[snum]==0:
            return True
        else:
            return False
    def indexoftop(self,snum):
        offset=snum*self.size
        return offset + self.sizes[snum]-1
    def push(self,val,snum):
        if self.isfull(snum):
            return " Stack is full"
        else:
            self.sizes[snum]+=1
            self.stack[self.indexoftop(snum)]=val
    def pop(self,snum):
        if self.isempty(snum):
            return "stack is empty"
        else:
            x=self.stack[self.indexoftop(snum)]
            self.stat[self.indexoftop(snum)]=0
            self.sizes[snum]-=1
            return x
    def peak(self,snum):
        if self.isempty(snum):
            return" Stack is empty"
        else:
            x=self.stack[self.indexoftop[snum]]
            return x
            

In [15]:
#minimum of stack
class Node():
    def __init__(self,val=None,next=None):
        self.val=val
        self.next=next
    def __str__(self):
        string=str(self.val)
        return string
class MinStack():
    def __init__(self):
        self.head=None
    def push(self,val):
        node=Node(val,self.head)
        self.head=node
    def pop(self):
        if self.head==None:
            return None
        else:
            x=self.head.val
            self.head=self.head.next
            return x
    def peak(self):
        if self.head==None:
            return None
        else:
            return self.head.val
    def min(self):
        if self.head==None:
            return None
        else:
            min=self.head.val
            temp=self.head
            while temp:
                if temp.val<min:
                    min=temp.val
                temp=temp.next
            return min
        
obj=MinStack()
obj.push(1)
obj.push(2)
obj.push(3)
obj.push(4)
obj.push(0)
print(obj)
print(obj.peak())
print(obj.min())
obj.pop()
print(obj)
print(obj.peak())
print(obj.min())      


0
0
4
1


In [93]:
#stack platea

class PS():
    def __init__(self,cap):
        self.cap=cap
        self.stacks=[]
    def __str__(self):
        return str(self.stacks)
    def push(self,val):
        if len(self.stacks)>0 and (len(self.stacks[-1]))< self.cap:
            self.stacks[-1].append(val)
        else:
            self.stacks.append([val])
    def pop(self):
        while len(self.stacks) and len(self.stacks[-1])==0:
            self.stacks.pop()
        if len(self.stacks)==0:
            return None
        else:
            return self.stacks[-1].pop
    def pop_at(self,snum):
        if len(self.stacks[snum])>0:
            return self.stacks[snum].pop()
        else:
            return None
        
cs=PS(3)
cs.push(1)
cs.push(2)
cs.push(3)
cs.push(4)
cs.push(5)
print(cs)
cs.pop()
print(cs)
print(cs.pop())

[[1, 2, 3], [4, 5]]
[[1, 2, 3], [4, 5]]
<built-in method pop of list object at 0x115797940>


In [94]:
#queues using stack

In [95]:
#Animal shelter

class Animal:
    def __init__(self):
        self.cats=[]
        self.dogs=[]
    def enq(self,animal,type):
        if type=='Cat':
            self.cats.append(animal)
        else:
            self.dogs.append(animal)
    def deqcat(self):
        
        if len(self.cats)==0:
            return None
        else:
            return self.cats.pop(0)
    def deqdog(self):
        if len(self.dogs)==0:
            return None
        else:
            return self.dogs.pop(0)
    def dqany(self):
        if len(self.cats)==0:
            return self.dogs.pop(0)
        else:
            return self.cats.pop(0)
cd=Animal()
cd,enq("Cat1","Cat")
cd.enq("dog1","Dog")
print(cd)
               

NameError: name 'enq' is not defined

# Tree
A tree is a nonlinear Ds with hieracical relationships b/w its element without any cycle 

Why tree: linear ds increase Time complexity when the size of data increases so we use tree (non linear) DS

example: file system in our computer

Root: top node without parent
Edge: a link b/w parent and child
leaf: a nofe which does not have children
sibling: children of same parent
Ancestor: parent, grand parent , great grand parent etc
Depth of node: length from root to node
height of node: 
depth of tree:
height of tree:



In [ ]:
class TreeNode:
    def __init__(self,data,children=[]):
        self.data=data
        self.children=children
    def __str__(self,level=0):
        ret= " "*level + str(self.data)+"\n"
        for child in self.children:
            ret+=child.__str__(level + 1)
        return ret
    def addchild(self,TreeNode):
        self.children.append(TreeNode)
tree=TreeNode("1",[])
prime=TreeNode("2",[])
comp=TreeNode("4",[])
tree.addchild(prime)
tree.addchild(comp)
prime1=TreeNode("3",[])
comp1=TreeNode("6",[])
prime.addchild(prime1)
comp.addchild(comp1)
print(tree)

#Binary tree

* each node have atmost 2 children


Types of binary tree
* Full Binary Tree: have 2 or 0 childern
* Perfect Binary Tree: have only 2 children and leaf nodes have 0 childre and all nodes at same level
* Complete Binary tree: all levels ar ecompletly filled expect last level

* Balanced Binary tree: all leaf nodes are located at same distance from root node

#binary tree
1. using linked list
2. using python list(array)

Tree Traversal:
1. Depth first search (DFS):
* Preorder traversa : root->left->right
* Inorder traversal: left->root->right
* Postorder traversal: left->right->root

2. Breadth first search:
* Level order traversal



In [ ]:
#creation of binary tree (linked list)
from collections import deque as q
class Treenode:
    def __init__(self,data):
        self.data=data
        self.left=None
        self.right=None
    
bt=Treenode("Hotel")
left=Treenode("tiffans")
right= Treenode("drinks")
bt.left=left
bt.right=right

def preorder(root):
    if not root:
        return 
    print(root.data)
    preorder(root.left)
    preorder(root.right)
preorder(bt)
print("\n")
def Inorder(root):
    if not root:
        return
    Inorder(root.left)
    print(root.data)
    Inorder(root.right)
Inorder(bt)
print("\n")
def postorder(root):
    if not root:
        return
    postorder(root.left)
    postorder(root.right)
    print(root.data)
    
postorder(bt)
    
def levelorder(root):
    if not root:
        return
    else:
        cq = q()
        cq.append(root)
        while len(cq) > 0:
            rt = cq.popleft()
            print(rt.data)
            if rt.left is not None:
                cq.append(rt.left)
            if rt.right is not None:
                cq.append(rt.right)

print("\n")                
levelorder(bt)

def search(root,x):
    if not root:
        return "No tree"
    else:
        cq=q()
        cq.append(root)
        while len(cq)>0:
            rt=cq.popleft()
            if rt.data==x:
                return "node found"
            else:
                if rt.left is not None:
                    cq.append(rt.left)
                if rt.right is not None:
                    cq.append(rt.right)
        return "not in tree"

search(bt,"drinks")
search(bt,"hello")              

#insert a node in binary tree
# a root node is blank
# we have to look for 1st vacant place

def insert(root,newn):
    if not root:
        root=Treenode(newn)
    else:
        cq=q()
        cq.append(root)
        while len(cq)>0:
            rt=cq.popleft()
            if rt.left is not None:
                cq.append(rt.left)
            else:
                rt.left=Treenode(newn)
                return "inserted"
            if rt.right is not None:
                cq.append(rt.right)
            else:
                rt.right=Treenode(newn)
                return "inserted"
        return "not inserted"
insert(bt,"idly")
insert(bt,"dosa")
insert(bt,"tea")
insert(bt,"coffee")
insert(bt,"puri")
print("\n")
levelorder(bt)
print("\n")
preorder(bt)
print("\n")
postorder(bt)
def delete_node(root, key):
    if root is None:
        return root

    if root.left is None and root.right is None:
        if root.data == key:
            return None
        else:
            return root

    key_node = None
    q = deque([root])
    while len(q) > 0:
        node = q.popleft()
        if node.data == key:
            key_node = node
        if node.left is not None:
            q.append(node.left)
        if node.right is not None:
            q.append(node.right)

    if key_node is not None:
        x = node.data
        delete_deepest(root, node)
        key_node.data = x

    return root

def delete_deepest(root, d_node):
    q = deque([root])
    while len(q) > 0:
        node = q.popleft()
        if node is d_node:
            node = None
            return
        if node.right is not None:
            if node.right is d_node:
                node.right = None
                return
            else:
                q.append(node.right)
        if node.left is not None:
            if node.left is d_node:
                node.left = None
                return
            else:
                q.append(node.left)
delete_node(bt,"dosa")
print("\n")
levelorder(bt)

In [ ]:
# tree using python list

class Tree:
    def __init__(self,size):
        self.list = size*[None]
        self.size = size
        self.index = 1
        
    def insert(self, newn):
        if self.size == self.index + 1:
            return "Tree is full"
        else:
            self.list[self.index] = newn
            self.index += 1
            return "inserted"
    
    def search(self, x):
        for i in range(len(self.list)):
            if self.list[i] == int(x):
                return "found in tree "
        return "not in tree"
    
    def preorder(self, index):
        if index > self.index:
            return
        print(self.list[index])
        self.preorder(index * 2)
        self.preorder(index * 2 + 1)
    def inorder(self,index):
        if index > self.index:
            return
        self.inorder(index*2)
        print(self.list[index])
        self.inorder(index*2 + 1)
    def postorder(self,index):
        if index > self.index:
            return
        self.inorder(index*2)
        self.inorder(index*2 + 1)
        print(self.list[index])
    
    def levelorder(self,index):
        for i in range(index,self.index+1):
            print(self.list[i])
    
    def delete(self,value):
        if self.index==0:
            return "empty tree"
        for i in range(1,self.index+1):
            if self.list[i]==value:
                self.list[i]=self.list[self.index]
                self.list[self.index]=None
                self.index-=1
                return "deleted"
        
        
bt = Tree(8)
bt.insert(1)
bt.insert(2)
bt.insert(3)
bt.insert(4)
bt.insert(5)
bt.insert(6)
bt.insert(7)

bt.preorder(1)
print("\n")
bt.inorder(1)
print("\n")
bt.postorder(1)
print("\n")
bt.levelorder(1)
print("\n")
bt.delete(3)
print("\n")
bt.levelorder(1)

#Binary search tree

* A BST is a Binary Tree
* All nodes in left sub tree are less than the parent node
* All nodes in right sub tree are greater than parent node
* faster in insertkion & deletion than binary trees

Operations:

* creation
* insertion
* deletion
* search
* 


In [ ]:
class bst:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None
        
    def bstinsert(self, data):
        if self.data is None:
            self.data = data
        elif data <= self.data:
            if self.left is None:
                self.left = bst(data)
            else:
                self.left.bstinsert(data)
        else:
            if self.right is None:
                self.right = bst(data)
            else:
                self.right.bstinsert(data)
        return "Node is inserted"
    
    def bstpreorder(self,root):
        if not root:
            return
        print(root.data)
        self.bstpreorder(root.left)
        self.bstpreorder(root.right)
    
    def bstinorder(self,root):
        if not root:
            return
        self.bstinorder(root.left)
        print(root.data)
        self.bstinorder(root.right)
    
    def bstpostorder(self,root):
        if not root:
            return
        self.bstpostorder(root.left)
        self.bstpostorder(root.right)
        print(root.data)
    
    def bstlevelorder(self,root):
        if root is None:
            return
        else:
            cq=q()
            cq.append(root)
            while len(cq) > 0:
                rt = cq.popleft()
                print(rt.data)
                if rt.left is not None:
                    cq.append(rt.left)
                if rt.right is not None:
                    cq.append(rt.right)
    
    def bstsearch(self,root,x):
        if root.data==x:
            return "element found"
        elif x<root.data:
            if root.left and root.left.data==x:
                return "element found"
            else:
                return self.bstsearch(root.left,x)
        else:
            if root.right and root.right.data==x:
                return "element found"
            else:
                return self.bstsearch(root.right,x)
        return "element not in bst"
    
    def bstdelete(self, root, x):
        if root is None:
            return root
        
        if x < root.data:
            root.left = self.bstdelete(root.left, x)
        elif x > root.data:
            root.right = self.bstdelete(root.right, x)
        else:
            if root.left is None:
                temp = root.right
                root = None
                return temp
            elif root.right is None:
                temp = root.left
                root = None
                return temp
            temp = self.getminnode(root.right)
            root.data = temp.data
            root.right = self.bstdelete(root.right, temp.data)
        return root
    
    def getminnode(self, root):
        while root.left is not None:
            root = root.left
        return root
        
b1 = bst(70)
b1.bstinsert(75)
b1.bstinsert(89)
b1.bstinsert(50)
b1.bstinsert(20)
b1.bstinsert(65)

print(b1.data)
b1.bstpreorder(b1)
print("\n")
b1.bstinorder(b1)
print("\n")
b1.bstpostorder(b1)
print("\n")
b1.bstlevelorder(b1)
print("\n")
print(b1.bstsearch(b1, 50))

print("\nDeleting 50")
b1.bstdelete(b1, 50)

print("\n")
b1.bstinorder(b1)


print("\nDeleting 700")
b1.bstdelete(b1, 70)

print("\n")
b1.bstlevelorder(b1)



#AVL Tree

An AVL tree is a self balancing BST where diff b/w height of left and right subtree can not be more than one for all node

why AVL Tree

If given numbers are in sorted order they going to form left skewed /right skewed tree, to remove skewness we need to balance the tree sucha sa AVL tree

Operation 

* create
* search
* traversal
* insert
* delete



In [ ]:
from collections import deque

class Avl:
    def __init__(self, data):
        self.left = None
        self.right = None
        self.data = data
        self.height = 1 

def Avlpreorder(root):
    if root is None:
        return
    print(root.data)
    Avlpreorder(root.left)
    Avlpreorder(root.right)

def Avlinorder(root):
    if root is None:
        return
    Avlinorder(root.left)
    print(root.data)
    Avlinorder(root.right)

def Avlpostorder(root):
    if root is None:
        return
    Avlpostorder(root.left)
    Avlpostorder(root.right)
    print(root.data)

def Avllevelrder(root):
    if not root:
        return
    else:
        cq = deque()
        cq.append(root)
        while len(cq) > 0:
            rt = cq.popleft()
            print(rt.data)
            if root.left is not None:
                cq.append(rt.left)
            if root.right is not None:
                cq.append(rt.right)

def Avlsearch(root, x):
    if root.data == x:
        return " element found"
    elif x < root.data:
        if root.left.data == x:
            return "element found"
        else:
            Avlsearch(root.left, x)
    else:
        if root.right.data == x:
            return "element found"
        else:
            Avlsearch(root.right, x)

def height(root):
    if not root:
        return 0
    return root.height

def rotright(node):
    nnode = node.left
    node.left = node.left.right
    nnode.right = node
    node.height = 1 + max(height(node.left), height(node.right))
    nnode.height = 1 + max(height(nnode.left), height(nnode.right))
    return nnode

def rotleft(node):
    nnode = node.right
    node.right = node.right.left
    nnode.left = node
    node.height = 1 + max(height(node.left), height(node.right))
    nnode.height = 1 + max(height(nnode.left), height(nnode.right))
    return nnode

def balance(root):
    if not root:
        return 0
    return height(root.left) - height(root.right)

def avlinsert(root, val):
    if not root:
        return Avl(val)
    elif val < root.data:
        root.left = avlinsert(root.left, val)
    else:
        root.right = avlinsert(root.right, val)
    root.height = 1 + max(height(root.left), height(root.right))
    bal = balance(root)
    if bal > 1 and val < root.left.data:
        return rotright(root)
    if bal > 1 and val > root.left.data:
        root.left = rotleft(root.left)
        return rotright(root)
    if bal < -1 and val > root.right.data:
        return rotleft(root)
    if bal < -1 and val < root.right.data:
        root.right = rotright(root.right)
        return rotleft(root)
    return root
def avldelete(root, key):
    if not root:
        return root

    elif key < root.data:
        root.left = avldelete(root.left, key)

    elif key > root.data:
        root.right = avldelete(root.right, key)

    else:
        if not root.left:
            temp = root.right
            root = None
            return temp

        elif not root.right:
            temp = root.left
            root = None
            return temp

        temp = minValueNode(root.right)
        root.data = temp.data
        root.right = avldelete(root.right, temp.data)

    if not root:
        return root

    root.height = 1 + max(height(root.left),
                         height(root.right))

    bal = balance(root)

    if bal > 1 and balance(root.left) >= 0:
        return rotright(root)

    if bal < -1 and balance(root.right) <= 0:
        return rotleft(root)

    if bal > 1 and balance(root.left) < 0:
        root.left = rotleft(root.left)
        return rotright(root)

    if bal < -1 and balance(root.right) > 0:
        root.right = rotright(root.right)
        return rotleft(root)

    return root
def minValueNode(node):
    current = node

    while current.left is not None:
        current = current.left

    return current


avl = Avl(10)


#binary heap

-> A binary heap is a Binary Tree 

-> it should be min heap / max heap, In a min heap, the key at rot must be min among all keys present in binary heap, same to all nodes

-> it must be a complete tree all levles expectthe last level and last leaf must tends to left as possible

why?

types:
* min heap: paretn node <= children
* max heap: parent node > children

Operations:
* creat
* peak
* min max
* traversal
* size
* insert
* delete


In [ ]:
class heap:
    def __init__(self,size):
        self.heap=[None]*(size+1)
        self.hsize=0
        self.maxsize=size+1

def heappeek(root):
    if not root:
        return
    else:
        return root.heap[1]

def heapsize(root):
    if not root:
        return 
    else:
        return root.hsize

def heaptrversal(root):
    if not root:
        return
    else:
        for i in range(1, root.hsize+1):
            print(root.heap[i])

def heapify(root,index,heaptype):
    pindex=int(index/2)
    if index <=2:
        return
    if heaptype=="Min":
        if root.heap[index]< root.heap[pindex]:
            root.heap[index], root.heap[pindex]=  root.heap[pindex],root.heap[index]
            heapify(root,pindex,heaptype)
    elif heaptype=="Max":
        if root.heap[index]>root.heap[pindex]:
            root.heap[index], root.heap[pindex]=  root.heap[pindex],root.heap[index]
            heapify(root,pindex,heaptype)

def insert(root,val,heaptype):
    if root.hsize+1== root.maxsize:
        return " Heap is full"
    root.heap[root.hsize+1]=val
    root.hsize+=1
    heapify(root,root.hsize,heaptype)
    return "Element is inserted into heap"

def heapifyextract(root,index,htype):
    lindex=index*2
    rindex= index*2+1
    swap=0
    if root.hsize <lindex:
        return
    elif root.hsize ==lindex:
        if htype=="Min":
            if root.heap[index]>root.heap[lindex]:
                root.heap[index],root.heap[lindex]=root.heap[lindex],root.heap[index]
            return
        else:
            if root.heap[index]<root.heap[lindex]:
                root.heap[index],root.heap[lindex]=root.heap[lindex],root.heap[index]
            return
    else:
        if htype=="Min":
            if root.heap[lindex]<root.heap[rindex]:
                if root.heap[index]>root.heap[lindex]:
                    root.heap[index],root.heap[lindex]=root.heap[lindex],root.heap[index]
                    heapifyextract(root,lindex,htype)
            else:
                if root.heap[index]>root.heap[rindex]:
                    root.heap[index],root.heap[rindex]=root.heap[rindex],root.heap[index]
                    heapifyextract(root,rindex,htype)
        else:
            if root.heap[lindex]>root.heap[rindex]:
                if root.heap[index]<root.heap[lindex]:
                    root.heap[index],root.heap[lindex]=root.heap[lindex],root.heap[index]
                    heapifyextract(root,lindex,htype)
            else:
                if root.heap[index]<root.heap[rindex]:
                    root.heap[index],root.heap[rindex]=root.heap[rindex],root.heap[index]
                    heapifyextract(root,rindex,htype)

def extract(root,heaptype):
    if not root:
        return "Heap is empty"
    minmax= root.heap[1]
    root.heap[1]= root.heap[root.hsize]
    root.heap[root.hsize]= None
    root.hsize-=1
    heapifyextract(root,1,heaptype)
    return minmax


#Trie
* Tree based DS to store data kin hiearch

Properities:
* used to store or search strings in a space and time efficently
* any node in trie can store non repatiitve multiple charecters
* every node stores link of next char of string
* every node keep track of end of a string

use case:
* spell checker
* auto completion

operations:
* create, insertion, search, deletion





In [ ]:
#Trie

class Trienode:
    def __init__(self):
        self.dic={}
        self.eos=None
class Trie:
    def __init__(self):
        self.root=Trienode()
    def Trieinsert(self,word):
        cur=self.root
        for i in word:
            ch=i
            node= cur.dic.get(ch)
            if node==None:
                node= Trienode()
                cur.dic.update({ch:node})
            cur=node
        cur.eos=True
        return "word inserted"
    def triesearch(self,x):
        cur=self.root
        for i in x:
            node=cur.dic.get(i)
            if node ==None:
                return False
            cur=node
        if cur.eos==True:
            return True
        else:
            return False
    
            
            
ct=Trie()
def triedelete(root,x,index):
    ch=x[index]
    node=root.dic.get(ch)
    dnode=False
    if len(node.dic)>1:
        triedelete(node,x,index+1)
        return False
    if index == len(x)-1:
        if len(node.dic)>=1:
            node.eos=False
            return False
        else:
            root.dic.pop(ch)
            return True
    if node.eos==True:
        triedelete(node,x,index+1)
        return False
    dnode=triedelete(node,word,index+1)
    if dnode==True:
        root.dic.pop(ch)
        return True
    else:
        return False
    

    
        
        

# Hashing 

Hash function

Key

Hash Value

Hash Table

Collision

# Sorting
Arrange data in paricular order increasing / decresing order

example: Microsoft excel sort function,sort in online applications

Types of sorting:

* space used
* stability

Space used:
1. In place sorting: no extra space requried (Buble sort)
2. Out place sorting: extra space requried (merge sort)

stability: (in DB Group by uses this)
1. Stable sorting: insertion sort ( identical number sequence is same as before sorting
2. unstable sorting: 

Ssorting Terminoliges:

Increasing order: 1,2,3,4,5

Decreasing order: 10,8,6,2,1

Non Increasing order: less than or equal to previous element: 10,8,6,6,2,1,1

Non Decreasing order: 1,2,2,3,4,4,5






In [ ]:
#bubble sort: known as sinking sort, we repeatedly  comapre pair of adjucent elements and swap them, by the end of each rotation largest element is moved to right side 

def bubble_sort(nums):
    for i in range(len(nums)-1):
        for j in range(len(nums)-i-1):
            if nums[j]> nums[j+1]:
                nums[j],nums[j+1]=nums[j+1],nums[j]
    return nums

x=[1,4,5,2,7,6,8,9,1,3]
bubble_sort(x)

# TC O(N^2)
# SC O(1)

# when to use: if it is already sorted in increasing order, space less
# when no to bubble sort: if lis is in decreassing order

In [ ]:
#Selection sort: divide array as sorted and unsorted,finfd the min element in unsorted array and add to sorted array

def selection_sort(nums):
    for i in range(len(nums)):
        for j in range(i+1,len(nums)):
            if nums[j]<nums[i]:
                nums[j],nums[i]=nums[i],nums[j]
    return nums
selection_sort(x)

# every time we find min element and add to sorted list
#TC : O(N^2)
#SC: O(1)
# when to use: space efficent
#when not to use: takes more time,large numbers of list so not use


In [ ]:
# insertion sort: dive into sorted and insorted , select element in unsorted array and place it in its original position

def insertion_sort(nums):
    for i in range(1,len(nums)):
        key=nums[i]
        j=i-1
        while  j>0 and key < nums[j]:
            nums[j+1]=nums[j]
        nums[j+1]=key
    return nums
insertion_sort(x)

#Tc o(n^2)
#sc : o(1)

#use: when w have continous flow of numbers and want to keep them sorted

        

In [ ]:
#bucket sort: create buckets and distrbute elements , sort buckets, merge buckets
#num of buckets = sqrt(len(nums)) round it to neares integer
#bucket selection: ceil(value* num of buckets / max value)
#sort each bucket
#merge all buckets
import math
def bucket_sort(nums):
    n= round(math.sqrt(len(nums)))
    maxval= max(nums)
    arr=[]
    for i in range(n):
        arr.append([])
    for j in nums:
        ind= math.ceil(j*n/maxval )
        arr[ind-1].append(j)
    for i in range(n):
        arr[i]= insertion_sort(arr[i])
    k=0
    for i in range(n):
        for j in range(len(arr[i])):
            nums[k]=arr[i][j]
            k+=1
    return nums
bucket_sort(x)

#TC: O(n^2)
# use quick sort instead od insertation, then TC will be O(nlogn)
#when to use: input uniformily distributed
 

In [ ]:
def merge(nums, l, n, r):
    n1 = n - l + 1
    n2 = r - n
    
    L = [0] * n1
    R = [0] * n2
    
    for i in range(0, n1):
        L[i] = nums[l + i]
    for j in range(0, n2):
        R[j] = nums[n + 1 + j]
    
    i = 0
    j = 0
    k = l
    
    while i < n1 and j < n2:
        if L[i] <= R[j]:
            nums[k] = L[i]
            i += 1
        else:
            nums[k] = R[j]
            j += 1
        k += 1
    
    while i < n1:
        nums[k] = L[i]
        i += 1
        k += 1
    
    while j < n2:
        nums[k] = R[j]
        j += 1
        k += 1

def merge_sort(nums, l, r):
    if l < r:
        n = (l + (r - 1)) // 2
        merge_sort(nums, l, n)
        merge_sort(nums, n + 1, r)
        merge(nums, l, n, r)
    
    return nums

x = [9, 4, 6, 3, 8, 2, 7, 1, 5, 0]
result = merge_sort(x, 0, len(x) - 1)
print(result)


In [ ]:
#quic sort

def quick_sort(nums):
    if len(nums) <= 1:
        return nums
    else:
        pivot = nums[0]  # Choose the first element as the pivot
        smaller = [x for x in nums[1:] if x <= pivot]
        greater = [x for x in nums[1:] if x > pivot]
        return quick_sort(smaller) + [pivot] + quick_sort(greater)

quick_sort(x)

In [ ]:
#heap sort

def heapify(nums, n, i):
    largest = i
    left = 2 * i + 1
    right = 2 * i + 2

    if left < n and nums[i] < nums[left]:
        largest = left

    if right < n and nums[largest] < nums[right]:
        largest = right

    if largest != i:
        nums[i], nums[largest] = nums[largest], nums[i]
        heapify(nums, n, largest)

def heap_sort(nums):
    n = len(nums)

    # Build a max heap
    for i in range(n // 2 - 1, -1, -1):
        heapify(nums, n, i)

    # Extract elements from the heap one by one
    for i in range(n - 1, 0, -1):
        nums[i], nums[0] = nums[0], nums[i]
        heapify(nums, i, 0)

    return nums

heap_sort(x)

Sorting Algorithms

Name Time Complexity Space Complexity Stable

Bubble Sort O(n²) 0(1) Yes

Selection Sort O(n²) 0(1) No

Insertion Sort O(n²) 0(1) Yes

Bucket Sort O(n logn) O(n) Yes

Merge Sort O(n logn) O(n) Yes

Quick Sort O(n logn) O(n) No

Heap Sort O(n logn) 0(1) No

In [ ]:
def linear_search(arr, target):
    for i in range(len(arr)):
        if arr[i] == target:
            return i  # Return the index of the target element
    return -1  # Target element not found

# Example usage:
arr = [4, 2, 9, 7, 5, 1]
target = 7
result = linear_search(arr, target)
if result != -1:
    print(f"Element {target} found at index {result}")
else:
    print("Element not found")


In [ ]:
def binary_search(arr, target):
    low = 0
    high = len(arr) - 1

    while low <= high:
        mid = (low + high) // 2
        if arr[mid] == target:
            return mid  # Return the index of the target element
        elif arr[mid] < target:
            low = mid + 1
        else:
            high = mid - 1
    
    return -1  # Target element not found

# Note: Binary search requires the input array to be sorted in ascending order
arr = [1, 2, 4, 5, 7, 9]
target = 7
result = binary_search(arr, target)
if result != -1:
    print(f"Element {target} found at index {result}")
else:
    print("Element not found")


# Graphs 

Graphs: It is a non linear DS, with nodes and edges, it is finate set of nodes and edges which connect each other (cylici or aclyic)

why: connecting Networks, shortest distance,

vertex: node of graph

edge: path b/w vertex

unweighted graph: no weights on edges

weighted graph: weights on edge

undirected graph: no direction on edges

directed graph: direction on edges

cyclic graph: atleast have one cycle in graph:

acylic graph: no cycle in graph

Tree: it is a directed acylic graph (special case)

Graph Types:
 1. directed graph:
 2. undirected graph:
 
1. direct graph:
 1. wieghted graph
 2. unweighted graph
   1. weighted graph: 
     1. postive graph:
     2. Negative graph:
2. undirected graph:
 1. wieghted graph
 2. unweighted graph 
   1. weighted graph: 
     1. postive graph:
     2. Negative graph:


Adjcent matrix: 2D matrix used to store vertex and edges (use this when it is complete graph)

Adjency list: collection of unorder list used to represent graph using linked list(as dictonary) ( usen when graph have few edges and vertex)






In [ ]:
#create a graph

class Graph:
    def __init__(self,gdict=None):
        if gdict is None:
            gdict={}
        self.gdict=gdict
    def addedge(self,vertex,edge):
        self.gdict[vertex].append(edge)
cd={ 'a':['b','c'],
    'b': ['a','d','e'],
    'c': ['a','e'],
    'd': ['b','e','f'],
    'e': ['d','f','c'],
    'f': ['d','e'] 
   }
graph= Graph(cd)
print(graph.gdict)
graph.addedge('e','a')
print(graph.gdict)

In [ ]:
class graph:
    def __init__(self):
        self.adj_list={}
        
    def add_vertex(self,vertex):
        if vertex not in self.adj_list.keys():
            self.adj_list[vertex]=[]
            return True
        return False
    def print_graph(self):
        for vertex in self.adj_list:
            print(vertex,":",self.adj_list[vertex])
    
    def add_edge(self,vertex1,vertex2):
        if vertex1 in self.adj_list.keys() and vertex2 in self.adj_list.keys():
            self.adj_list[vertex1].append(vertex2)
            self.adj_list[vertex2].append(vertex1)
            return True
        return False
    def remove_edge(self,vertex1,vertex2):
        if vertex1 in self.adj_list.keys() and vertex2 in self.adj_list.keys():
            self.adj_list[vertex1].remove(vertex2)
            self.adj_list[vertex2].remove(vertex1)
            return True
        return False
    def remove_vertex(self, vertex):
        if vertex in self.adj_list.keys():
            for other_vertex in self.adj_list[vertex]:
                self.adj_list[other_vertex].remove(vertex)
            del self.adj_list[vertex]
            return True
        return False
    
        
cg=graph()
cg.add_vertex("A")
cg.add_vertex("B")
cg.add_vertex("C")
cg.add_edge("A","B")
cg.add_edge("B","C")
cg.print_graph()

In [ ]:
#BFS
class Graph:
    def __init__(self,gdict=None):
        if gdict is None:
            gdict={}
        self.gdict=gdict
    def addedge(self,vertex,edge):
        self.gdict[vertex].append(edge)
    def bfs(self,vertex):
        visted=[vertex]
        queue=[vertex]
        while queue:
            devertex= queue.pop(0)
            print(devertex)
            for adjvertex in self.gdict[devertex]:
                if adjvertex not in visted:
                    visted.append(adjvertex)
                    queue.append(adjvertex)
                
    
cd={ 'a':['b','c'],
    'b': ['a','d','e'],
    'c': ['a','e'],
    'd': ['b','e','f'],
    'e': ['d','f','c'],
    'f': ['d','e'] 
   }
g=Graph(cd)
g.bfs('a')

In [ ]:
#DFS
#create a graph

class Graph:
    def __init__(self,gdict=None):
        if gdict is None:
            gdict={}
        self.gdict=gdict
    def addedge(self,vertex,edge):
        self.gdict[vertex].append(edge)
        
    def dfs(self,vertex):
        stack=[vertex]
        visited=[vertex]
        while stack:
            p=stack.pop()
            print(p)
            for i in self.gdict[p]:
                if i not in visited:
                    visited.append(i)
                    stack.append(i)
cd={ 'a':['b','c'],
    'b': ['a','d','e'],
    'c': ['a','e'],
    'd': ['b','e','f'],
    'e': ['d','f','c'],
    'f': ['d','e'] 
   }
g=Graph(cd)
g.dfs('a')


# Toplogical sort:
 sorts given actions in such a way that if there is dependency of one action on another, the dependency actor always comes later than its parent action
 
Algorithm:

if vertex depomds on current vertex

     go to that vertex and
     then came back to currentvertex
else

    push currentvertex to stack

In [ ]:
from collections import defaultdict

class Graph:
    def __init__(self, nvertices):
        self.graph = defaultdict(list)
        self.nvertices = nvertices

    def add_edge(self, vertex, edge):
        self.graph[vertex].append(edge)

    def topological_util(self, v, visited, stack):
        visited.append(v)

        for i in self.graph[v]:
            if i not in visited:
                self.topological_util(i, visited, stack)

        stack.append(v)

    def topological_sort(self):
        visited = []
        stack = []

        for k in list(self.graph):
            if k not in visited:
                self.topological_util(k, visited, stack)

        stack.reverse()
        print(stack)

g = Graph(8)
g.add_edge("A", "C")
g.add_edge("C", "E")
g.add_edge("E", "H")
g.add_edge("E", "F")
g.add_edge("F", "G")
g.add_edge("B", "C")
g.add_edge("B", "D")
g.add_edge("D", "F")
g.topological_sort()

#TC: O(V+E)


# SSSPP
Single source shortest path problem

finding a path between a given vertex to other vertices in a graph such that the total distance between them is minimum



# BFS for SSSPP

BFS
enqueue any starting vertex

    while queue is not empty

        p = dequeue ()
        if p is unvisited
            mark it visited
            enqueue all adjacent unvisited vertices of p
            update parent of adjacent vertices to curVertex

In [ ]:
from collections import defaultdict

class Graph:
    def __init__(self, gdict=None):
        if gdict is None:
            gdict = {}
        self.gdict = gdict
    
    def bfs(self, start, end):
        visited = set()
        queue = [[start]]

        if start == end:
            return f"Start and end vertices are the same: {start}"

        while queue:
            path = queue.pop(0)
            node = path[-1]

            if node not in visited:
                adjacent_nodes = self.gdict.get(node, [])
                for adjacent_node in adjacent_nodes:
                    new_path = list(path)
                    new_path.append(adjacent_node)
                    queue.append(new_path)

                    if adjacent_node == end:
                        return new_path

                visited.add(node)

        return "No path found between the given vertices."

graph_dict = {
    'a': ['b', 'c'],
    'b': ['a', 'd', 'e'],
    'c': ['a', 'e'],
    'd': ['b', 'e', 'f'],
    'e': ['d', 'f', 'c'],
    'f': ['d', 'e']
}

g = Graph(graph_dict)
path = g.bfs("a", "f")
print(path)


# BFS for ssspp will only work with unweighted graphs(directed and undirected)

# why it is not work with weighted

BFS goes like level order, when it goes with weight, so we  may might not get minimal path


# DFS not work for SSSPP
it goes as far as from source

# Dijkstra Algorithm
It is used to find shorest path for weighted graphs

Algorithm:

start will be 0

mark remaining vertex as infinity

calculate distance to next vertex if distance is min than vertex distance replace with mini distance 

after calculating distance form all neighbour mark strart vertex as visited and reprat it to all it neighbour vertices

In [ ]:
import heapq

class Edge:
    def __init__(self, weight, start, target):
        self.weight = weight
        self.start = start
        self.target = target

class Node:
    def __init__(self, name):
        self.name = name
        self.visited = False
        self.predecessor = None
        self.neighbours = []
        self.min_distance = float("inf")

    def __lt__(self, other):
        return self.min_distance < other.min_distance

    def add_edge(self, weight, destination):
        ed = Edge(weight, self, destination)
        self.neighbours.append(ed)

class Dijkstra:
    def __init__(self):
        self.heap = []

    def calc(self, start_vertex):
        start_vertex.min_distance = 0
        heapq.heappush(self.heap, start_vertex)

        while self.heap:
            actual_vertex = heapq.heappop(self.heap)

            for edge in actual_vertex.neighbours:
                start = edge.start
                target = edge.target
                new_distance = start.min_distance + edge.weight

                if new_distance < target.min_distance:
                    target.min_distance = new_distance
                    target.predecessor = start

                    # Re-add the updated node to the heap
                    heapq.heappush(self.heap, target)

            actual_vertex.visited = True

    def get_shortest_path(self, vertex):
        print(f"Shortest path to {vertex.name}:")
        print(f"Minimum distance: {vertex.min_distance}")

        actual_vertex = vertex
        path = []

        while actual_vertex is not None:
            path.append(actual_vertex.name)
            actual_vertex = actual_vertex.predecessor

        path.reverse()
        print("Path:", ' -> '.join(path))


# Create nodes
a = Node("A")
b = Node("B")
c = Node("C")
d = Node("D")
e = Node("E")

# Create edges
a.add_edge(5, b)
a.add_edge(1, c)
b.add_edge(3, c)
b.add_edge(2, d)
c.add_edge(2, d)
c.add_edge(4, e)
d.add_edge(1, e)

# Initialize Dijkstra's algorithm
dijkstra = Dijkstra()
dijkstra.calc(a)

# Get the shortest path from A to E
dijkstra.get_shortest_path(e)


# dijkstra can not deal with negative cycle so we neeed to use bellman frod algorithm

Bellman Ford Algorithm

Single Source Shortest Path Algorithm

Graph Type BFS Dijkstra Bellman Ford

Unweighted - undirected OK OK OK

Unweighted - directed OK OK OK

Positive weighted - undirected X OK OK

Positive - weighted - directed X OK OK

Negative - weighted - undirected X OK OK

Negative - weighted - directed X OK OK

Negative Cycle X X OK

Bellman Ford Algorithm

Bellman Ford algorithm is used to find single source shortest path problem. If there is a negative cycle it catches it and report its existence.

If the distance of destination vertex > (distance ofsource vertex + weight between source and destination

vertex):

    Update distance of destination vertex to (distance ofsource vertex + weight between source and destinationvertex)
    
why v-1 times:
the  max number of node b/w teo nodes is v-1

In [ ]:
class Graph:
    def __init__(self, vertices):
        self.V = vertices
        self.graph = []

    def add_edge(self, u, v, w):
        self.graph.append([u, v, w])

    def bellman_ford(self, src):
        # Step 1: Initialize distance from source to all other vertices as infinite
        distance = [float("inf")] * self.V
        distance[src] = 0

        # Step 2: Relax all edges |V| - 1 times
        for _ in range(self.V - 1):
            for u, v, w in self.graph:
                if distance[u] != float("inf") and distance[u] + w < distance[v]:
                    distance[v] = distance[u] + w

        # Step 3: Check for negative-weight cycles
        for u, v, w in self.graph:
            if distance[u] != float("inf") and distance[u] + w < distance[v]:
                print("Graph contains negative-weight cycle")
                return

        # Step 4: Print the shortest distances
        self.print_solution(distance)

    def print_solution(self, distance):
        print("Vertex\tDistance from Source")
        for i in range(self.V):
            print(f"{i}\t\t{distance[i]}")


# Create a graph with 5 vertices
g = Graph(5)

# Add edges to the graph (u, v, w) -> edge from u to v with weight w
g.add_edge(0, 1, -1)
g.add_edge(0, 2, 4)
g.add_edge(1, 2, 3)
g.add_edge(1, 3, 2)
g.add_edge(1, 4, 2)
g.add_edge(3, 2, 5)
g.add_edge(3, 1, 1)
g.add_edge(4, 3, -3)

# Run Bellman-Ford algorithm with source vertex 0
g.bellman_ford(0)


BFS vs Dijkstra vs Bellman Ford

BFS Dijkstra Bellman Ford

Time complexity O(V²) O(V²) O(VE)

Space complexity O(E) OM OM

Implementation Easy Moderate Moderate Limitation Not work for weighted graph Not work for negative cycle N/A

OK OK OK

Unweighted graph Use this as time complexity is good and Not e as implementation not Not use as time complexity
easy to implement is bad

easy
X OK OK

Weighted graph Use as time complexity is Not use as time complexity

Not supported

better than Bellman is bad

X X OK

Negative Cycle Use this as others not

Not supported Not supported

support

# Floyd Warshall

* used to find minimum path for each vertx
* distance for vertex to it self is 0
* if we do not have direct path we set it to infinity
* fill the value with weights
* if distance b/w 2 vertices > the distance  from short vertex a\+ distaance from destination vertex then update it

# Why (It covers all below cases, so it is very accurate)
* the vertex is not reacble is infinity (do not run alg)
* direct link b/w vertices
* connected via of other vertex

# Negative cycles

it can not used for negative cyle because we never vist vertecx twice so it unable to catch negative cyle


In [ ]:
def floyd_warshall(graph):
    num_vertices = len(graph)
    distance = [[float('inf') if i != j else 0 for j in range(num_vertices)] for i in range(num_vertices)]
    
    # Initialize the distance matrix with the weights of the graph
    for u in range(num_vertices):
        for v, weight in graph[u]:
            distance[u][v] = weight
    
    # Main algorithm loop
    for k in range(num_vertices):
        for i in range(num_vertices):
            for j in range(num_vertices):
                if distance[i][j] > distance[i][k] + distance[k][j]:
                    distance[i][j] = distance[i][k] + distance[k][j]
    
    return distance

# Example usage
graph = [
    [(1, 3), (2, 6)],     # Vertex 0
    [(2, 2)],             # Vertex 1
    [(3, 1)],             # Vertex 2
    [(1, 4), (0, 2)]      # Vertex 3
]

result = floyd_warshall(graph)
for row in result:
    print(row)

#TC : O(V^3)

# Minimum Spanning Tree

A minimum spanning tree(MST) is a subset of the edge of conneected , weighted & undirected graph

* connectes all vertices
* no cycle
* minimu total edge

# Disjoint set
A ds that keep track of set of elements which are partitioned into number of disjoint and non overlapping sets and each set have eepresntative which helps in identifying that sets

* MakeSet(N): used to create inital set
* union(x,y): merge two given set
* findSet(x): return the set name in which this element is present



In [ ]:
class DisjointSet:
    def __init__(self, vertices):
        self.vertices = vertices
        self.parent = {}
        for v in vertices:
            self.parent[v] = v
        self.rank = dict.fromkeys(vertices, 0)

    def find(self, item):
        if self.parent[item] == item:
            return item
        else:
            return self.find(self.parent[item])

    def union(self, x, y):
        xroot = self.find(x)
        yroot = self.find(y)
        
        if self.rank[xroot] < self.rank[yroot]:
            self.parent[xroot] = yroot
        elif self.rank[xroot] > self.rank[yroot]:
            self.parent[yroot] = xroot
        else:
            self.parent[yroot] = xroot
            self.rank[xroot] += 1

# Example usage
vertices = ["A", "B", "C", "D", "E"]
ds = DisjointSet(vertices)
ds.union("A", "B")
print(ds.find("A"))


# Kruskal's Algorithm
It is a greedy algorithm

It finds a minimum spanning tree for weighted undirected graphs in two ways

Add increasing cost edges at each step

Avoid any cycle at each step

In [ ]:
class DisjointSet:
    def __init__(self, vertices):
        self.parent = {}
        self.rank = {}
        for v in vertices:
            self.parent[v] = v
            self.rank[v] = 0
    
    def find(self, item):
        if self.parent[item] != item:
            self.parent[item] = self.find(self.parent[item])
        return self.parent[item]
    
    def union(self, x, y):
        xroot = self.find(x)
        yroot = self.find(y)
        
        if self.rank[xroot] < self.rank[yroot]:
            self.parent[xroot] = yroot
        elif self.rank[xroot] > self.rank[yroot]:
            self.parent[yroot] = xroot
        else:
            self.parent[yroot] = xroot
            self.rank[xroot] += 1


def kruskal(graph):
    # Sort the edges in non-decreasing order of their weights
    edges = sorted(graph, key=lambda x: x[2])
    
    mst = []
    disjoint_set = DisjointSet(vertices)
    
    for edge in edges:
        u, v, weight = edge
        if disjoint_set.find(u) != disjoint_set.find(v):
            mst.append(edge)
            disjoint_set.union(u, v)
    
    return mst


# Example usage
vertices = ["A", "B", "C", "D", "E"]
graph = [
    ("A", "B", 3),
    ("A", "C", 1),
    ("B", "C", 4),
    ("B", "D", 2),
    ("C", "D", 5),
    ("C", "E", 6),
    ("D", "E", 7)
]

mst = kruskal(graph)
for edge in mst:
    print(edge)


# Prims Algorithm
is a greedy algorithm
finds a minimum spanning tree for weighted undirected graphs in following ways
1. Take any vertex as a source set its weight to 0 and all other vertices' weight to infinity
2. For every adjacent vertices if the current weight is more than current edge then we set it
to current edge
3. Then we mark current vertex as visited
4. Repeat these steps for all vertices in increasing order of weight

In [ ]:
import heapq


def prim(graph):
    start_vertex = list(graph.keys())[0]  # Choose any starting vertex
    
    mst = []  # Minimum Spanning Tree
    visited = set([start_vertex])  # Visited vertices
    edges = [(weight, start_vertex, neighbor) for neighbor, weight in graph[start_vertex]]
    heapq.heapify(edges)  # Create a min-heap from the edges
    
    while edges:
        weight, u, v = heapq.heappop(edges)  # Extract the edge with the minimum weight
        if v not in visited:
            visited.add(v)
            mst.append((u, v, weight))
            for neighbor, weight in graph[v]:
                if neighbor not in visited:
                    heapq.heappush(edges, (weight, v, neighbor))
    
    return mst


# Example usage
graph = {
    "A": [("B", 3), ("C", 1)],
    "B": [("A", 3), ("C", 4), ("D", 2)],
    "C": [("A", 1), ("B", 4), ("D", 5), ("E", 6)],
    "D": [("B", 2), ("C", 5), ("E", 7)],
    "E": [("C", 6), ("D", 7)]
}

mst = prim(graph)
for edge in mst:
    print(edge)


# Greedy Algorithm

* build the solution piece by piece
* in each step most suitable solution
* 

used in :
* Insertion sort: "
* Selection sort
* Topological sort
* prims Algorithm
* kruskal Algorithm

* Activly selection problem
* coin change problem
* Fractional Knapsack problem


In [ ]:
def activitySelection(start, end):
    activities = sorted(zip(start, end), key=lambda x: x[1])  # Sort activities by end time
    selected_activities = [activities[0]]  # Select the first activity with the earliest end time
    last_end_time = activities[0][1]
    
    for activity in activities[1:]:
        start_time, end_time = activity
        if start_time >= last_end_time:  # If the activity's start time is after the last selected activity's end time
            selected_activities.append(activity)
            last_end_time = end_time
    
    return selected_activities


In [ ]:
def coinChange(coins, amount):
    dp = [float('inf')] * (amount + 1)
    dp[0] = 0

    for i in range(1, amount + 1):
        for coin in coins:
            if coin <= i:
                dp[i] = min(dp[i], dp[i - coin] + 1)

    return dp[amount] if dp[amount] != float('inf') else -1


In [ ]:
class Item:
    def __init__(self, value, weight):
        self.value = value
        self.weight = weight
        self.value_weight_ratio = value / weight

def fractional_knapsack(items, capacity):
    # Sort items based on their value-to-weight ratio in descending order
    sorted_items = sorted(items, key=lambda item: item.value_weight_ratio, reverse=True)
    
    total_value = 0.0
    knapsack = []

    for item in sorted_items:
        if capacity >= item.weight:
            # Add the entire item to the knapsack
            knapsack.append(item)
            total_value += item.value
            capacity -= item.weight
        else:
            # Add a fraction of the item to the knapsack based on the remaining capacity
            fraction = capacity / item.weight
            item_fraction = Item(item.value * fraction, item.weight * fraction)
            knapsack.append(item_fraction)
            total_value += item.value * fraction
            capacity = 0
            break
    
    return total_value, knapsack

# Example usage
items = [
    Item(60, 10),
    Item(100, 20),
    Item(120, 30)
]
capacity = 50

max_value, knapsack_items = fractional_knapsack(items, capacity)

# Print the maximum achievable value and the selected items in the knapsack
print("Maximum Value:", max_value)
print("Knapsack Items:")
for item in knapsack_items:
    print("Value:", item.value, " Weight:", item.weight)


# Divide and conquer



In [11]:
from collections import Counter

class Solution:
    def minOperations(self, nums):
        x = dict(Counter(nums))
        x1 = list(x.values())
        c = 0

        for i in x1:
            if i==1:
                return -1
            if i % 3 == 0:
                    c += i // 3
            else:
                y = i // 3
                z = False

                for j in range(y, 0, -1):
                    if (i - (j * 3)) % 2 == 0:
                        z = True
                        k = j
                        m = (i - (j * 3)) // 2
                        break

                if z:
                    c += k + m
                else:
                    c += i // 2

        return c



# Test case
nums = [19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19]
obj = Solution()
result = obj.minOperations(nums)
print(result)


5
